### ISSUE TITLE
cpdef declarations

### ISSUE THREAD

**Issue by weisenburgers** [ikinsella/trefide#1]
Hi, I had to modify the cpdef declarations in /solvers/temporal.pxd for cython to compile. I have attached the patch for it.

[cpdef_declarations.patch.zip](https://github.com/ikinsella/trefide/files/2439493/cpdef_declarations.patch.zip)

**Comment by smu160** [comment]
Hi,

Thank you for raising this issue. We're currently making some changes, but you can look at the new master branch for the latest working version.

Feel free to submit pull requests via GitHub.
