### ISSUE TITLE
ICC error when using pip to set up

### ISSUE THREAD

**Issue by sharonjsu** [ikinsella/trefide#3]
When I run 
``` 
LDSHARED="icc -shared" CC=icc CXX=icpc pip install -e /path/to/trefide
```
I receive this error.

```
                                                                                                                                                      ^
    
    compilation aborted for trefide/solvers/temporal.cpp (code 2)
    /usr/lib/python3.6/distutils/extension.py:131: UserWarning: Unknown Extension options: 'package_data'
      warnings.warn(msg)
    /home/clandininlab/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/clandininlab/trefide/trefide/decimation.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    /home/clandininlab/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/clandininlab/trefide/trefide/pmd.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    warning: trefide/pmd.pyx:656:47: the result of using negative indices inside of code sections marked as 'wraparound=False' is undefined
    warning: trefide/pmd.pyx:656:64: the result of using negative indices inside of code sections marked as 'wraparound=False' is undefined
    /home/clandininlab/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/clandininlab/trefide/trefide/solvers/space/lagrangian.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    /home/clandininlab/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/clandininlab/trefide/trefide/solvers/temporal.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    warning: trefide/solvers/temporal.pyx:113:6: Function 'cpdas' previously declared as 'cpdef'
    warning: trefide/solvers/temporal.pyx:155:6: Function 'cps_cpdas' previously declared as 'cpdef'
    warning: trefide/solvers/temporal.pyx:196:6: Function 'lpdas' previously declared as 'cpdef'
    warning: trefide/solvers/temporal.pyx:369:6: Function 'lipm' previously declared as 'cpdef'
    /home/clandininlab/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/clandininlab/trefide/trefide/temporal.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    error: command 'icc' failed with exit status 2
    
    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/clandininlab/trefide/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in /home/clandininlab/trefide/

```

Can anybody help me with this? Not sure what's going on.
-------

Edit: Fixed by downgrading from ubuntu 18 to 16.04.

**Comment by ghost** [comment]
This is still an issue on some Linux versions (i.e. CentOS 6.8) when running the same ICC command. Please advise.


      trefide/solvers/space/lagrangian.cpp(2730): error: argument of type "const double *" is incompatible with parameter of type "double *"
              __pyx_v_status = DR2_TV(__pyx_v_d1, __pyx_v_d2, (&(*((double const  *) ( /* dim=0 */ ((char *) (((double const  *) __pyx_v_y.data) + __pyx_t_7)) )))), __pyx_v_lambda_tv, __pyx_v_lambda_tv, 1.0, 1.0, (&(*((double *) ( /* dim=0 */ ((char *) (((double *) __pyx_v_y_hat.data) + __pyx_t_8)) )))), 1, 1, (&(*((double *) ( /* dim=0 */ ((char *) (((double *) __pyx_v_info.data) + __pyx_t_9)) )))));
                                                              ^

    compilation aborted for trefide/solvers/space/lagrangian.cpp (code 2)
    /home/anaconda3/envs/hydra/lib/python3.7/distutils/extension.py:131: UserWarning: Unknown Extension options: 'package_data'
      warnings.warn(msg)
    error: command 'icc' failed with exit status 2

**Comment by rotemov** [comment]
Any solutions other than downgrading? I am running on Ubuntu 18.04 as instructed.

`rotemov@rotemov********:~/trefide$ LDSHARED="icc -shared" CC=icc CXX=icpc pip install -e ~/trefide/
Obtaining file:///home/rotemov/trefide
Installing collected packages: trefide
  Running setup.py develop for trefide
    ERROR: Command errored out with exit status 1:
     command: /home/rotemov/anaconda3/envs/invivo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/rotemov/trefide/setup.py'"'"'; __file__='"'"'/home/rotemov/trefide/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/rotemov/trefide/
    Complete output (13 lines):
    running develop
    running egg_info
    writing trefide.egg-info/PKG-INFO
    writing dependency_links to trefide.egg-info/dependency_links.txt
    writing top-level names to trefide.egg-info/top_level.txt
    reading manifest file 'trefide.egg-info/SOURCES.txt'
    writing manifest file 'trefide.egg-info/SOURCES.txt'
    running build_ext
    building 'trefide.solvers.temporal' extension
    icc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/rotemov/anaconda3/envs/invivo/lib/python3.6/site-packages/numpy/core/include -I/home/rotemov/anaconda3/envs/invivo/include/python3.6m -c trefide/solvers/temporal.cpp -o build/temp.linux-x86_64-3.6/trefide/solvers/temporal.o -O3 -I/home/rotemov/anaconda3/envs/invivo/include -I/home/rotemov/trefide/include -I/home/rotemov/trefide/external/proxtv -I/home/rotemov/trefide/external/glmgen/include -D NOMATLAB=1 -mkl=sequential -qopenmp
    /home/rotemov/anaconda3/envs/invivo/lib/python3.6/distutils/extension.py:131: UserWarning: Unknown Extension options: 'package_data'
      warnings.warn(msg)
    error: command 'icc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/rotemov/anaconda3/envs/invivo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/rotemov/trefide/setup.py'"'"'; __file__='"'"'/home/rotemov/trefide/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`

**Comment by smu160** [comment]
Hi @rotemov,

Thank you for raising this issue. There is a docker image that you can use if you want to avoid building everything from source. Let me know if that works better for you.

Thank you!

**Comment by rotemov** [comment]
I succeeded using it with the docker image (on a windows host), however I need it installed as a package as I am working on the https://github.com/adamcohenlab/invivo-imaging pipeline.
Please update if you know how to solve this issue.

On another note I think that in your latest update the Makefile is not the src directory, thus step 4 of the instructions should be modified.

**Comment by smu160** [comment]
Thank you for bringing this up. I'll look into it today, and I'll update you.

**Comment by rotemov** [comment]
After further digging I think this error might be related to not having Intel Parallel Studios XE. Is it possible this is also a prerequisite?

**Comment by smu160** [comment]
You should be able to compile the dependencies and install the package just using g++ and gcc. Can you try running:

```make clean && make all -j $(nproc) && pip uninstall trefide -y && pip install .```

**Comment by rotemov** [comment]
Thanks! I'll update Sunday if it works.

**Comment by rotemov** [comment]
This is the output.
`(invivo) rotemov@r********:~/Programs/trefide/src$ make all -j $(nproc)
cd proxtv; make;
cd glmgen; make;
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/home/rotemov/Programs/trefide/src/glmgen'
mkdir -p lib
icpc -mkl=sequential -qopenmp -O3 -fPIC -I/home/rotemov/Programs/trefide/src/proxtv -I/home/rotemov/Programs/trefide/src/glmgen/include/ -D NOMATLAB=1    -c -o utils/welch.o utils/welch.cpp
make: icpc: Command not found
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/home/rotemov/Programs/trefide/src/proxtv'
icpc -mkl=sequential -O3 -fPIC -D NOMATLAB=1    -c -o condat_fast_tv.o condat_fast_tv.cpp
<builtin>: recipe for target 'utils/welch.o' failed
make: *** [utils/welch.o] Error 127
make: *** Waiting for unfinished jobs....
make[1]: icpc: Command not found
mkdir -p obj
<builtin>: recipe for target 'condat_fast_tv.o' failed
make[1]: *** [condat_fast_tv.o] Error 127
make[1]: Leaving directory '/home/rotemov/Programs/trefide/src/proxtv'
Makefile:17: recipe for target 'proxtv/libproxtv.so' failed
make: *** [proxtv/libproxtv.so] Error 2
cd obj; icc  -c -fPIC ../src/csparse/*.c -I../include/
/bin/sh: 1: icc: not found
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 127
make[1]: Leaving directory '/home/rotemov/Programs/trefide/src/glmgen'
Makefile:20: recipe for target 'glmgen/lib/libglmgen.so' failed
make: *** [glmgen/lib/libglmgen.so] Error 2
make: *** wait: No child processes.  Stop.
`

I'm working on installing Intel Parallel Studios XE, I'll update when I do. For some reason their download servers are not working at the moment.

**Comment by rotemov** [comment]
I solved the issue here in a fairly unelegant work around. 
1. I installed the Intel Parallel Studio XE software as icc and icpc compilers are unavailable with out it.
2. source <intel_install_dir>/parallel_studio_xe_2020.2.108/bin/psxevars.sh
3. source ~/.bashrc (file was updated according to supplied instructions)
4. continue previous steps from make all

The crux is that in order to import the trefide package I have to run 2,3 before activating my conda env. 

Something else I can across that might interest you is that you may be using the gcc command with icc additions for example 'gcc -qopenmp'. This is not valid syntax and it might be working in your environment because of a specific configuration that makes icc run when you use gcc.

Thanks again for your support!

**Comment by jeremyforest** [comment]
Had to reinstall on ubuntu 20.04 and encountered the same problems with icc. Using only gcc and g++ did not work for me either but @rotemov solution worked. Thanks all for the help !

**Comment by smu160** [comment]
@rotemov Sorry for the delay! I'll try installing on a fresh install of ubuntu today to try to reproduce the issues you brought up. Thank you for the updates and for providing your solution!

**Comment by smu160** [comment]
@rotemov Thank you again for bringing up this issue. We have updated the build from source instructions. Unfortunately, I was unable to to reproduce the issue on a fresh install of Ubuntu 20.04, as well as Manjaro. After taking another look at the output you provided, I think you may be using an older version of trefide. If you run into any issues in the future, please feel free to open a new issue.

Thank you!
