### ISSUE TITLE
Docker import trefide.pmd failed

### ISSUE THREAD

**Issue by RenieWell** [ikinsella/trefide#4]
I am appriciate that you provided the Docker image in dockerhub, it would be very helpul. 
So, I tried to run the docker image after typing `docker pull ikinsella/trefide`.
However, I found that the docker image can not import the trefide correctly. When I ran the test notebook in `demos\Demo Compression & Denoising.ipynb`, it failed in line 7, which is `trefide.pmd import batch_decompose`, and the error is `cannot import name 'batch_decompose'`.
Can please you help me?

**Comment by smu160** [comment]
Hi,

Thank you for raising this issue. We're currently making some changes, but you can look at the new master branch for setting up the latest version. There is a docker image that you can use if you want to avoid building everything from source. The updated instructions are in the readme as well.

Feel free to create a new issue if you have trouble getting anything working.
