### ISSUE TITLE
Troubleshooting installation and publish Dockerfile

### ISSUE THREAD

**Issue by nik-sm** [ikinsella/trefide#5]
Hello,

Thanks for making your project open source! 

I'm trying to install from source, and I'm having some difficulty.

Basically the net result is that when trying to run your demo matrix decomposition, I get:
```
ImportError                               Traceback (most recent call last)
  <ipython-input-14-71405471def8> in <module>()
         5 # Preprocessing Dependencies
         6 from trefide.utils import psd_noise_estimate
----> 7 from trefide.pmd import determine_thresholds
ImportError: /trefide_vol/trefide/pmd.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z9batch_pmdiiiiiiPPdS0_S0_S0_Pmddmmmmd
```

After some digging, this looks to be the "name-mangled" symbol for the function `batch_pmd`, and based on this, I'm thinking that perhaps this is an issue in one of the Makefiles and how files are linked during compilation.

When I try to run the demo using the image provided at https://hub.docker.com/r/ikinsella/trefide, I also get an `ImportError`, though it does not complain about that mangled symbol.

Would it be possible for you to publish your Dockerfile? I think this would be helpful both for me to build from source, and for possibly debugging that second `ImportError`.

Thanks!

**Comment by jw3132** [comment]
We are working on to improve the code. By far, the recommended way to install and use this software is  using conda environment in Ubuntu OS. Please follow the guide in https://github.com/ikinsella/trefide to install using conda. If you want to use docker, please use ubuntu docker image and then install using conda.

Thanks.

Jian

**Comment by nik-sm** [comment]
Ok I see, thank you for the info.

I think I mostly have things correctly installed - in case it is useful, I attached the Dockerfile and docker-compose.yml that I am using 

(I had to add '.txt' extension so that I could attach them to a github comment). 

However my jupyter kernel dies towards the end of the notebook at `comparison_plot(...)`. I am running Docker on macOS and I have given the engine 7GB of memory and 3GB of swap, but perhaps this is still not enough for the demo PMD notebook. I'm going to try on a computer with more resources. (I'm also used to pip instead of conda, so apologies if I am using conda in strange ways in this Dockerfile)

From the root of the repo:

`docker-compose up --build trefide`

Then jupyter should be running at `localhost:8888`.

[docker-compose.yml.txt](https://github.com/ikinsella/trefide/files/3258147/docker-compose.yml.txt)
[Dockerfile.txt](https://github.com/ikinsella/trefide/files/3258148/Dockerfile.txt)

**Comment by smu160** [comment]
Hi,

Thank you for raising this issue. We're currently making some changes, but you can look at the new master branch for setting up the latest version. There is a docker image that you can use if you want to avoid building everything from source. The instructions are in the updated readme as well.

Feel free to create a new issue if you have trouble getting that particular branch working.
