### ISSUE TITLE
Error with conda install

### ISSUE THREAD

**Issue by pjsteffan93** [ikinsella/trefide#6]
Hello, 
  I am attempting to run the notebook "Demo PMD Compression & Denoising" after having installed Trefide 2.0 via conda and am getting some import errors.  It appears as though several of the functions that the notebook is looking for in trefide.pmd are actually stored in trefide.denoiser.  The only function I cannot seem to locate is determine_thresholds.  Is it possible that I'm using an outdated build, or maybe I've made a simple mistake?  Any insight you could provide would be appreciated! 

Thanks much, 
  Paul

**Comment by jw3132** [comment]
The notebook “Demo PMD Compression & Denoising” has been deprecated in version 2.0. 
Trefide package has been restructured since version 2.0 and is different from v1.0. Please use Test_3D_Decomp.ipynb as the demo.

determine_thresholds is in trefide/pmd.pyx file.

Thanks.

Jian

**Comment by pjsteffan93** [comment]
Hello again! 
  Thank you for your quick reply! I am sorry it has taken me this long to respond, but I got caught up doing experiments.  

  I looked in pmd.pyx and did not find determine_thresholds defined anywhere.  Moreover, using git grep, I could not find an definition for determine_thresholds anywhere.  Would it be possible for you to double check pmd.pyx and add the definition for determine_thresholds, if necessary?  I'd really appreciate it! 

--pjs

**Comment by pjsteffan93** [comment]
Addendum to my last comment: 
  So notice in the Test_3D_Decomp.ipynb there is code that looks as thought it achieves what determine_thresholds would do, just not implemented as a function.  Is that the case?   

In truth, I am asking all of these questions not because I am trying to run the Test_3D_Decomp.ipynb but rather the "Demo Compression and Denoising.ipynb" included in the funimag repository.  It was in running that code that I first had the issue with finding determine_thresholds.  But, since that came from trefide, I tried to find the solution by looking at the demos associated with this repository and posted an issue here. 

Thanks in advance for your help!  Once we can get them up and running, I think these packages will be really powerful tools for analyzing data in our lab! 

--pjs

**Comment by jeremyforest** [comment]
Hi @pjsteffan93 
I had the same problem as you. I think funimag is using a previous build of trefide. When you go through the code from the pmd branch of trefide, you can find the determine_threshold function. For some reason it's been pruned from the last commit and replaced by the code in the notebook that does the same thing.
I think you should be able to copy/paste the determine_threshold function from the older commit and recompile the c++ code in the last commit to get that function working again.

Thanks for the author for making this open source though, it's really good at cleaning voltage imaging data !

-Jeremy

**Comment by pjsteffan93** [comment]
Thanks for your reply, Jeremy!  I was able to adapt the funimag code using the new trefide notebook as a guide and that did the trick!
