### ISSUE TITLE
PackagesNotFoundError for trefide

### ISSUE THREAD

**Issue by sppmg** [ikinsella/trefide#8]
Hi, look like `trefide` not exist in `jw3132` channel now.
Can you fix it ?
Thanks !

Error log:
```
(base) C:\Users\User>conda create -n trefide_py36 python=3.6 trefide -c jw3132 -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - trefide

Current channels:

  - https://conda.anaconda.org/jw3132/win-64
  - https://conda.anaconda.org/jw3132/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
......
```

**Comment by smu160** [comment]
Hi,

Thank you for raising this issue. We're currently making some changes, but you can look at the optimizations branch for setting up the latest version. There is a docker image that you can use if you want to avoid building everything from source. The instructions are in the optimizations branch readme as well. 

Let me know if you have any issues getting that particular branch working.

EDIT:
The master branch has been updated, so you can use everything there now.
